# ベースとなるDockerイメージを指定する。
#:(タグ)でバージョンを指定できる。イメージ名はDockerHub上で探す
#nginx:latestで最新版を指定できる
#alpine:Alpine Linuxのことで軽量なLinuxディストリビューションイメージがくっついてくる
#　そのため、DockerコンテナをLinuxサーバーライクに扱うことができる
#かなり軽量であるため、Dockerイメージのサイズを抑えることができる。

FROM nginx:1.21.1-alpine